import type { AppState } from '@/hooks/useAppContext';

export const seedData: AppState = {
  currentUser: {
    id: 'u1',
    name: 'Alex Johnson',
    role: 'Senior Recruiter',
    avatar: 'AJ',
    email: 'alex@talentflow.com',
    department: 'Talent Acquisition',
  },
  team: [
    {
      id: 'u1',
      name: 'Alex Johnson',
      role: 'Senior Recruiter',
      avatar: 'AJ',
      email: 'alex@talentflow.com',
      department: 'Talent Acquisition',
    },
    {
      id: 'u2',
      name: 'Maria Santos',
      role: 'Recruiter',
      avatar: 'MS',
      email: 'maria@talentflow.com',
      department: 'Talent Acquisition',
    },
    {
      id: 'u3',
      name: 'James Lee',
      role: 'HR Manager',
      avatar: 'JL',
      email: 'james@talentflow.com',
      department: 'Human Resources',
    },
  ],
  clients: [
    {
      id: 'c1',
      name: 'TechCorp Inc.',
      industry: 'Technology',
      contact: 'Sarah Williams',
      email: 'sarah@techcorp.com',
      phone: '+1 555-0101',
      website: 'https://techcorp.com',
      location: 'San Francisco, CA',
      status: 'active',
      jobsCount: 5,
      createdAt: '2024-01-15',
    },
    {
      id: 'c2',
      name: 'FinanceHub',
      industry: 'Finance',
      contact: 'Robert Brown',
      email: 'robert@financehub.com',
      phone: '+1 555-0102',
      location: 'New York, NY',
      status: 'active',
      jobsCount: 3,
      createdAt: '2024-02-20',
    },
    {
      id: 'c3',
      name: 'HealthPlus',
      industry: 'Healthcare',
      contact: 'Emily Davis',
      email: 'emily@healthplus.com',
      location: 'Boston, MA',
      status: 'active',
      jobsCount: 2,
      createdAt: '2024-03-10',
    },
  ],
  jobs: [
    {
      id: 'j1',
      title: 'Senior Frontend Developer',
      clientId: 'c1',
      location: 'San Francisco, CA',
      type: 'full-time',
      status: 'open',
      department: 'Engineering',
      salary: '$120k - $160k',
      description: 'We are looking for a Senior Frontend Developer to join our team.',
      requirements: ['React', 'TypeScript', '5+ years experience'],
      recruiterId: 'u1',
      createdAt: '2024-06-01',
      applicantsCount: 12,
    },
    {
      id: 'j2',
      title: 'Product Manager',
      clientId: 'c1',
      location: 'Remote',
      type: 'full-time',
      status: 'open',
      department: 'Product',
      salary: '$110k - $140k',
      description: 'Looking for an experienced Product Manager.',
      requirements: ['3+ years PM experience', 'Agile', 'Data-driven'],
      recruiterId: 'u2',
      createdAt: '2024-06-10',
      applicantsCount: 8,
    },
    {
      id: 'j3',
      title: 'Financial Analyst',
      clientId: 'c2',
      location: 'New York, NY',
      type: 'full-time',
      status: 'open',
      department: 'Finance',
      salary: '$80k - $100k',
      description: 'Seeking a Financial Analyst.',
      requirements: ['CFA', 'Excel', '2+ years experience'],
      recruiterId: 'u1',
      createdAt: '2024-06-15',
      applicantsCount: 6,
    },
    {
      id: 'j4',
      title: 'Nurse Practitioner',
      clientId: 'c3',
      location: 'Boston, MA',
      type: 'full-time',
      status: 'open',
      department: 'Clinical',
      salary: '$90k - $115k',
      description: 'Looking for a certified Nurse Practitioner.',
      requirements: ['NP License', 'Clinical experience', 'Patient care'],
      recruiterId: 'u2',
      createdAt: '2024-06-20',
      applicantsCount: 4,
    },
    {
      id: 'j5',
      title: 'Backend Engineer',
      clientId: 'c1',
      location: 'San Francisco, CA',
      type: 'contract',
      status: 'on-hold',
      department: 'Engineering',
      salary: '$100k - $130k',
      description: 'Contract position for Backend Engineer.',
      requirements: ['Node.js', 'PostgreSQL', '3+ years'],
      recruiterId: 'u1',
      createdAt: '2024-05-01',
      applicantsCount: 9,
    },
  ],
  candidates: [
    {
      id: 'ca1',
      name: 'David Chen',
      email: 'david@example.com',
      phone: '+1 555-1001',
      location: 'San Francisco, CA',
      title: 'Frontend Developer',
      skills: ['React', 'TypeScript', 'CSS'],
      experience: 6,
      education: 'BS Computer Science',
      avatar: 'DC',
      status: 'active',
      source: 'LinkedIn',
      createdAt: '2024-06-02',
    },
    {
      id: 'ca2',
      name: 'Priya Patel',
      email: 'priya@example.com',
      phone: '+1 555-1002',
      location: 'Remote',
      title: 'Product Manager',
      skills: ['Roadmapping', 'Agile', 'Jira'],
      experience: 4,
      education: 'MBA',
      avatar: 'PP',
      status: 'active',
      source: 'Referral',
      createdAt: '2024-06-12',
    },
    {
      id: 'ca3',
      name: 'Michael Torres',
      email: 'michael@example.com',
      location: 'New York, NY',
      title: 'Financial Analyst',
      skills: ['Excel', 'Financial Modeling', 'SQL'],
      experience: 3,
      education: 'BS Finance',
      avatar: 'MT',
      status: 'active',
      source: 'Indeed',
      createdAt: '2024-06-16',
    },
    {
      id: 'ca4',
      name: 'Sarah Kim',
      email: 'sarah@example.com',
      location: 'Boston, MA',
      title: 'Nurse Practitioner',
      skills: ['Patient Care', 'Clinical Assessment', 'EMR'],
      experience: 5,
      education: 'MSN',
      avatar: 'SK',
      status: 'active',
      source: 'Job Board',
      createdAt: '2024-06-21',
    },
    {
      id: 'ca5',
      name: 'Ryan Nguyen',
      email: 'ryan@example.com',
      location: 'San Francisco, CA',
      title: 'Backend Engineer',
      skills: ['Node.js', 'PostgreSQL', 'Docker'],
      experience: 4,
      education: 'BS Computer Science',
      avatar: 'RN',
      status: 'active',
      source: 'GitHub',
      createdAt: '2024-05-02',
    },
  ],
  applications: [
    { id: 'ap1', jobId: 'j1', candidateId: 'ca1', stage: 'interview', appliedAt: '2024-06-03', rating: 4 },
    { id: 'ap2', jobId: 'j2', candidateId: 'ca2', stage: 'screening', appliedAt: '2024-06-13' },
    { id: 'ap3', jobId: 'j3', candidateId: 'ca3', stage: 'applied', appliedAt: '2024-06-17' },
    { id: 'ap4', jobId: 'j4', candidateId: 'ca4', stage: 'offer', appliedAt: '2024-06-22', rating: 5 },
    { id: 'ap5', jobId: 'j5', candidateId: 'ca5', stage: 'applied', appliedAt: '2024-05-03' },
    { id: 'ap6', jobId: 'j1', candidateId: 'ca5', stage: 'screening', appliedAt: '2024-06-05' },
  ],
  interviews: [
    {
      id: 'iv1',
      applicationId: 'ap1',
      jobId: 'j1',
      candidateId: 'ca1',
      interviewerId: 'u1',
      type: 'video',
      scheduledAt: '2024-07-10T10:00:00',
      duration: 60,
      status: 'scheduled',
    },
    {
      id: 'iv2',
      applicationId: 'ap4',
      jobId: 'j4',
      candidateId: 'ca4',
      interviewerId: 'u2',
      type: 'onsite',
      scheduledAt: '2024-07-12T14:00:00',
      duration: 90,
      status: 'scheduled',
    },
    {
      id: 'iv3',
      applicationId: 'ap6',
      jobId: 'j1',
      candidateId: 'ca5',
      interviewerId: 'u1',
      type: 'phone',
      scheduledAt: '2024-07-08T09:00:00',
      duration: 30,
      status: 'completed',
      feedback: 'Strong candidate, good technical skills.',
      rating: 4,
    },
  ],
};
