export const seedData = {
  jobs: [
    {
      id: 'job-1',
      title: 'Senior Frontend Engineer',
      clientId: 'client-1',
      location: 'New York, NY',
      type: 'full-time',
      status: 'active',
      salary: '$120k - $150k',
      description: 'We are looking for a Senior Frontend Engineer to join our team and help build world-class user interfaces.',
      requirements: ['5+ years React experience', 'TypeScript proficiency', 'CSS/design systems knowledge'],
      postedDate: '2024-01-10',
    },
    {
      id: 'job-2',
      title: 'Product Manager',
      clientId: 'client-2',
      location: 'San Francisco, CA',
      type: 'full-time',
      status: 'active',
      salary: '$130k - $160k',
      description: 'Seeking an experienced Product Manager to lead our core product initiatives.',
      requirements: ['3+ years PM experience', 'Technical background preferred', 'Strong communication skills'],
      postedDate: '2024-01-12',
    },
    {
      id: 'job-3',
      title: 'DevOps Engineer',
      clientId: 'client-1',
      location: 'Remote',
      type: 'full-time',
      status: 'active',
      salary: '$110k - $140k',
      description: 'Join our infrastructure team to build and maintain scalable cloud systems.',
      requirements: ['AWS/GCP experience', 'Kubernetes & Docker', 'CI/CD pipeline management'],
      postedDate: '2024-01-15',
    },
    {
      id: 'job-4',
      title: 'UX Designer',
      clientId: 'client-3',
      location: 'Austin, TX',
      type: 'contract',
      status: 'paused',
      salary: '$90k - $110k',
      description: 'Looking for a creative UX Designer to craft intuitive user experiences.',
      requirements: ['Figma proficiency', 'User research experience', 'Portfolio required'],
      postedDate: '2024-01-08',
    },
  ],
  candidates: [
    {
      id: 'cand-1',
      name: 'Sarah Chen',
      email: 'sarah.chen@email.com',
      phone: '+1 555-0101',
      location: 'New York, NY',
      currentTitle: 'Frontend Engineer',
      skills: ['React', 'TypeScript', 'CSS', 'GraphQL'],
      status: 'active',
      notes: 'Strong candidate with excellent portfolio.',
    },
    {
      id: 'cand-2',
      name: 'Marcus Johnson',
      email: 'marcus.j@email.com',
      phone: '+1 555-0102',
      location: 'San Francisco, CA',
      currentTitle: 'Product Manager',
      skills: ['Product Strategy', 'Agile', 'Data Analysis', 'Roadmapping'],
      status: 'active',
      notes: 'Excellent PM experience at Series B startups.',
    },
    {
      id: 'cand-3',
      name: 'Priya Patel',
      email: 'priya.patel@email.com',
      phone: '+1 555-0103',
      location: 'Remote',
      currentTitle: 'DevOps Engineer',
      skills: ['AWS', 'Kubernetes', 'Terraform', 'Python'],
      status: 'active',
      notes: 'Solid DevOps background with strong cloud skills.',
    },
    {
      id: 'cand-4',
      name: 'James Rivera',
      email: 'james.r@email.com',
      phone: '+1 555-0104',
      location: 'Austin, TX',
      currentTitle: 'UX Designer',
      skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
      status: 'active',
      notes: 'Creative designer with strong portfolio.',
    },
    {
      id: 'cand-5',
      name: 'Emily Watson',
      email: 'emily.w@email.com',
      phone: '+1 555-0105',
      location: 'New York, NY',
      currentTitle: 'Full Stack Developer',
      skills: ['React', 'Node.js', 'PostgreSQL', 'TypeScript'],
      status: 'active',
      notes: 'Well-rounded full stack developer.',
    },
  ],
  applications: [
    { id: 'app-1', candidateId: 'cand-1', jobId: 'job-1', stage: 'Interview', appliedDate: '2024-01-11' },
    { id: 'app-2', candidateId: 'cand-2', jobId: 'job-2', stage: 'Offer', appliedDate: '2024-01-13' },
    { id: 'app-3', candidateId: 'cand-3', jobId: 'job-3', stage: 'Screening', appliedDate: '2024-01-16' },
    { id: 'app-4', candidateId: 'cand-4', jobId: 'job-4', stage: 'Applied', appliedDate: '2024-01-09' },
    { id: 'app-5', candidateId: 'cand-5', jobId: 'job-1', stage: 'Applied', appliedDate: '2024-01-12' },
    { id: 'app-6', candidateId: 'cand-1', jobId: 'job-3', stage: 'Hired', appliedDate: '2024-01-10' },
    { id: 'app-7', candidateId: 'cand-2', jobId: 'job-1', stage: 'Rejected', appliedDate: '2024-01-11' },
  ],
  clients: [
    {
      id: 'client-1',
      name: 'TechCorp Inc.',
      industry: 'Technology',
      website: 'techcorp.com',
      phone: '+1 555-1000',
      email: 'hr@techcorp.com',
      status: 'active',
      openJobs: 2,
      notes: 'Long-term client with multiple open positions.',
    },
    {
      id: 'client-2',
      name: 'StartupXYZ',
      industry: 'SaaS',
      website: 'startupxyz.io',
      phone: '+1 555-2000',
      email: 'talent@startupxyz.io',
      status: 'active',
      openJobs: 1,
      notes: 'Fast-growing Series B startup.',
    },
    {
      id: 'client-3',
      name: 'Design Studio Co.',
      industry: 'Creative Agency',
      website: 'designstudio.co',
      phone: '+1 555-3000',
      email: 'jobs@designstudio.co',
      status: 'active',
      openJobs: 1,
      notes: 'Boutique design agency.',
    },
  ],
  interviews: [
    {
      id: 'int-1',
      candidateId: 'cand-1',
      jobId: 'job-1',
      type: 'Technical Interview',
      status: 'scheduled',
      date: '2024-02-01',
      time: '10:00 AM',
    },
    {
      id: 'int-2',
      candidateId: 'cand-2',
      jobId: 'job-2',
      type: 'Final Round',
      status: 'scheduled',
      date: '2024-02-03',
      time: '2:00 PM',
    },
    {
      id: 'int-3',
      candidateId: 'cand-3',
      jobId: 'job-3',
      type: 'Phone Screen',
      status: 'completed',
      date: '2024-01-25',
      time: '11:00 AM',
    },
  ],
  teamMembers: [
    {
      id: 'team-1',
      name: 'Alex Johnson',
      email: 'alex.johnson@company.com',
      role: 'Admin',
      permissions: ['all'],
    },
    {
      id: 'team-2',
      name: 'Maria Garcia',
      email: 'maria.garcia@company.com',
      role: 'Recruiter',
      permissions: ['candidates', 'jobs', 'interviews'],
    },
    {
      id: 'team-3',
      name: 'David Kim',
      email: 'david.kim@company.com',
      role: 'Manager',
      permissions: ['candidates', 'jobs', 'interviews', 'reports'],
    },
  ],
};
