import type { AppState } from '@/types';

const now = new Date().toISOString();

export const seedData: AppState = {
  currentUser: {
    id: 'user-1',
    name: 'Alex Johnson',
    email: 'alex@talentflow.com',
    role: 'Admin',
    avatar: 'AJ',
  },
  candidates: [
    {
      id: 'cand-1',
      name: 'Sarah Chen',
      email: 'sarah.chen@email.com',
      phone: '+1 (555) 100-0001',
      status: 'interview',
      currentRole: 'Senior Frontend Developer',
      avatar: 'SC',
      location: 'San Francisco, CA',
      skills: ['React', 'TypeScript', 'Node.js'],
      experience: 6,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cand-2',
      name: 'Marcus Williams',
      email: 'marcus.w@email.com',
      phone: '+1 (555) 100-0002',
      status: 'screening',
      currentRole: 'Product Manager',
      avatar: 'MW',
      location: 'New York, NY',
      skills: ['Agile', 'Roadmapping', 'Analytics'],
      experience: 4,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cand-3',
      name: 'Priya Patel',
      email: 'priya.p@email.com',
      phone: '+1 (555) 100-0003',
      status: 'offer',
      currentRole: 'Data Scientist',
      avatar: 'PP',
      location: 'Austin, TX',
      skills: ['Python', 'ML', 'SQL'],
      experience: 5,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cand-4',
      name: 'James Okonkwo',
      email: 'james.o@email.com',
      status: 'hired',
      currentRole: 'DevOps Engineer',
      avatar: 'JO',
      location: 'Seattle, WA',
      skills: ['AWS', 'Docker', 'Kubernetes'],
      experience: 7,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cand-5',
      name: 'Emily Rodriguez',
      email: 'emily.r@email.com',
      status: 'new',
      currentRole: 'UX Designer',
      avatar: 'ER',
      location: 'Chicago, IL',
      skills: ['Figma', 'User Research', 'Prototyping'],
      experience: 3,
      createdAt: now,
      updatedAt: now,
    },
  ],
  jobs: [
    {
      id: 'job-1',
      title: 'Senior Frontend Engineer',
      department: 'Engineering',
      location: 'San Francisco, CA',
      type: 'Full-time',
      status: 'open',
      description: 'We are looking for a senior frontend engineer to join our growing team.',
      requirements: ['5+ years React', 'TypeScript', 'GraphQL'],
      salary: { min: 140000, max: 180000, currency: 'USD' },
      clientId: 'client-1',
      openings: 2,
      filled: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'job-2',
      title: 'Product Manager',
      department: 'Product',
      location: 'New York, NY',
      type: 'Full-time',
      status: 'open',
      description: 'Lead product strategy and roadmap for our core platform.',
      requirements: ['3+ years PM experience', 'B2B SaaS', 'Data-driven'],
      salary: { min: 120000, max: 160000, currency: 'USD' },
      clientId: 'client-2',
      openings: 1,
      filled: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'job-3',
      title: 'Data Scientist',
      department: 'Data',
      location: 'Austin, TX',
      type: 'Full-time',
      status: 'open',
      description: 'Build ML models and data pipelines for our analytics platform.',
      requirements: ['Python', 'ML frameworks', 'SQL'],
      salary: { min: 130000, max: 170000, currency: 'USD' },
      clientId: 'client-1',
      openings: 1,
      filled: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'job-4',
      title: 'DevOps Engineer',
      department: 'Infrastructure',
      location: 'Remote',
      type: 'Full-time',
      status: 'closed',
      description: 'Manage and scale our cloud infrastructure.',
      requirements: ['AWS', 'Terraform', 'CI/CD'],
      salary: { min: 125000, max: 165000, currency: 'USD' },
      openings: 1,
      filled: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'job-5',
      title: 'UX Designer',
      department: 'Design',
      location: 'Chicago, IL',
      type: 'Full-time',
      status: 'open',
      description: 'Design intuitive user experiences for our product suite.',
      requirements: ['Figma', 'User research', '3+ years experience'],
      salary: { min: 100000, max: 130000, currency: 'USD' },
      clientId: 'client-3',
      openings: 1,
      filled: 0,
      createdAt: now,
      updatedAt: now,
    },
  ],
  clients: [
    {
      id: 'client-1',
      name: 'TechCorp Solutions',
      industry: 'Software',
      website: 'https://techcorp.example.com',
      contactName: 'Dana Kim',
      contactTitle: 'VP of Engineering',
      phone: '+1 (555) 200-0001',
      email: 'dana.kim@techcorp.example.com',
      status: 'active',
      createdAt: now,
    },
    {
      id: 'client-2',
      name: 'Finova Partners',
      industry: 'Finance',
      website: 'https://finova.example.com',
      contactName: 'Robert Steele',
      contactTitle: 'Head of Talent',
      phone: '+1 (555) 200-0002',
      email: 'r.steele@finova.example.com',
      status: 'active',
      createdAt: now,
    },
    {
      id: 'client-3',
      name: 'HealthBridge Inc.',
      industry: 'Healthcare',
      website: 'https://healthbridge.example.com',
      contactName: 'Monica Reyes',
      contactTitle: 'HR Director',
      phone: '+1 (555) 200-0003',
      email: 'm.reyes@healthbridge.example.com',
      status: 'active',
      createdAt: now,
    },
  ],
  interviews: [
    {
      id: 'int-1',
      candidateId: 'cand-1',
      jobId: 'job-1',
      type: 'video',
      status: 'scheduled',
      scheduledAt: new Date(Date.now() + 86400000).toISOString(),
      notes: 'Focus on system design and React architecture.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'int-2',
      candidateId: 'cand-2',
      jobId: 'job-2',
      type: 'phone',
      status: 'completed',
      scheduledAt: new Date(Date.now() - 86400000).toISOString(),
      notes: 'Initial screening call.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'int-3',
      candidateId: 'cand-3',
      jobId: 'job-3',
      type: 'technical',
      status: 'scheduled',
      scheduledAt: new Date(Date.now() + 172800000).toISOString(),
      notes: 'Technical assessment — ML coding challenge.',
      createdAt: now,
      updatedAt: now,
    },
  ],
  team: [
    {
      id: 'team-1',
      name: 'Jordan Lee',
      email: 'jordan.lee@talentflow.com',
      phone: '+1 (555) 300-0001',
      role: 'Senior Recruiter',
      department: 'Talent Acquisition',
      avatar: 'JL',
      createdAt: now,
    },
    {
      id: 'team-2',
      name: 'Taylor Morgan',
      email: 'taylor.morgan@talentflow.com',
      phone: '+1 (555) 300-0002',
      role: 'Recruiter',
      department: 'Talent Acquisition',
      avatar: 'TM',
      createdAt: now,
    },
    {
      id: 'team-3',
      name: 'Casey Rivera',
      email: 'casey.rivera@talentflow.com',
      phone: '+1 (555) 300-0003',
      role: 'HR Manager',
      department: 'Human Resources',
      avatar: 'CR',
      createdAt: now,
    },
  ],
};
